# no global "commands", so this toml denotes to a python-function-style job
script = "demo2.py"
function = "tf1"

[params]
ct1 = 1

[params.product]
ct4 = ["x"]
ct5 = ["y", "z"]

[params.zip]
ct2 = ["a", "b"]
ct3 = ["c", "d"]  